version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./urls.db:/app/urls.db
    environment:
      - DATABASE_URL=sqlite:///./urls.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/docs')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 